/**
 * Injects Vercel/build environment variables into environment.prod.ts
 * Usage: NG_APP_API_URL=https://api.example.com/api/v1 node scripts/inject-env.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.join(__dirname, '../src/environments/environment.prod.ts');

const apiUrl =
  process.env.NG_APP_API_URL ||
  process.env.API_URL ||
  '/api/v1';

const googleClientId =
  process.env.NG_APP_GOOGLE_CLIENT_ID ||
  process.env.GOOGLE_CLIENT_ID ||
  '';

const escape = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

const content = `// Auto-generated by scripts/inject-env.mjs — do not edit on CI
export const environment = {
  production: true,
  apiUrl: '${escape(apiUrl)}',
  googleClientId: '${escape(googleClientId)}',
  appName: 'AI UPSC Study OS',
};
`;

fs.writeFileSync(outFile, content, 'utf8');
console.log('[inject-env] apiUrl:', apiUrl);
console.log('[inject-env] wrote', outFile);
