"""initial schema autogen

Revision ID: 0622f5d1172d
Revises: d11e0f7b09b9
Create Date: 2026-07-07 18:59:39.627551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0622f5d1172d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types only if they don't exist to avoid DuplicateObject errors when running migrations multiple times
    op.execute("""DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole') THEN
            CREATE TYPE userrole AS ENUM ('STUDENT','ADMIN','MODERATOR');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'examtarget') THEN
            CREATE TYPE examtarget AS ENUM ('UPSC','MPSC','BOTH');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'examtype') THEN
            CREATE TYPE examtype AS ENUM ('PRELIMS','MAINS','INTERVIEW');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'questiontype') THEN
            CREATE TYPE questiontype AS ENUM ('MCQ','DESCRIPTIVE','ESSAY','CASE_STUDY');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'planstatus') THEN
            CREATE TYPE planstatus AS ENUM ('ACTIVE','COMPLETED','PAUSED','ABANDONED');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'subjectcategory') THEN
            CREATE TYPE subjectcategory AS ENUM ('GS1','GS2','GS3','GS4','CSAT','OPTIONAL','CURRENT_AFFAIRS');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'topicstatus') THEN
            CREATE TYPE topicstatus AS ENUM ('NOT_STARTED','IN_PROGRESS','COMPLETED','NEEDS_REVISION');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'evaluationstatus') THEN
            CREATE TYPE evaluationstatus AS ENUM ('PENDING','PROCESSING','COMPLETED','FAILED');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notetype') THEN
            CREATE TYPE notetype AS ENUM ('MANUAL','AI_GENERATED','SUMMARY','FLASHCARD','MIND_MAP','REVISION');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'revisionstatus') THEN
            CREATE TYPE revisionstatus AS ENUM ('PENDING','COMPLETED','SKIPPED','OVERDUE');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'taskstatus') THEN
            CREATE TYPE taskstatus AS ENUM ('PENDING','IN_PROGRESS','COMPLETED','SKIPPED','RESCHEDULED');
        END IF;
    END$$;""")

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', 'MODERATOR', name='userrole'), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('exam_target', sa.Enum('UPSC', 'MPSC', 'BOTH', name='examtarget'), nullable=False),
    sa.Column('daily_study_hours', sa.Integer(), nullable=False),
    sa.Column('exam_year', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('total_study_hours', sa.Integer(), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('current_affairs',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('related_subjects', sa.JSON(), nullable=False),
    sa.Column('related_topics', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('ai_relevance_explanation', sa.Text(), nullable=True),
    sa.Column('upsc_relevance_score', sa.String(length=10), nullable=True),
    sa.Column('prelims_relevant', sa.Boolean(), nullable=False),
    sa.Column('mains_relevant', sa.Boolean(), nullable=False),
    sa.Column('mains_angles', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_current_affairs_id'), 'current_affairs', ['id'], unique=False)
    op.create_index(op.f('ix_current_affairs_published_date'), 'current_affairs', ['published_date'], unique=False)
    op.create_table('daily_study_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('study_hours', sa.Float(), nullable=False),
    sa.Column('topics_studied', sa.Integer(), nullable=False),
    sa.Column('revisions_done', sa.Integer(), nullable=False),
    sa.Column('notes_created', sa.Integer(), nullable=False),
    sa.Column('pyqs_attempted', sa.Integer(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('tasks_total', sa.Integer(), nullable=False),
    sa.Column('productivity_score', sa.Float(), nullable=False),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_study_logs_date'), 'daily_study_logs', ['date'], unique=False)
    op.create_index(op.f('ix_daily_study_logs_id'), 'daily_study_logs', ['id'], unique=False)
    op.create_index(op.f('ix_daily_study_logs_user_id'), 'daily_study_logs', ['user_id'], unique=False)
    op.create_table('mock_tests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('attempted_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('wrong_answers', sa.Integer(), nullable=False),
    sa.Column('unattempted', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('obtained_marks', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('time_taken_minutes', sa.Integer(), nullable=True),
    sa.Column('question_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('analysis', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_tests_id'), 'mock_tests', ['id'], unique=False)
    op.create_index(op.f('ix_mock_tests_user_id'), 'mock_tests', ['user_id'], unique=False)
    op.create_table('pyqs',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('exam', sa.Enum('PRELIMS', 'MAINS', 'INTERVIEW', name='examtype'), nullable=False),
    sa.Column('exam_name', sa.String(length=100), nullable=False),
    sa.Column('paper', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('subtopic', sa.String(length=255), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('MCQ', 'DESCRIPTIVE', 'ESSAY', 'CASE_STUDY', name='questiontype'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('correct_answer', sa.String(length=10), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('word_limit', sa.Integer(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('model_answer', sa.Text(), nullable=True),
    sa.Column('answer_structure', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('trend_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('related_topics', sa.JSON(), nullable=False),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pyqs_exam'), 'pyqs', ['exam'], unique=False)
    op.create_index(op.f('ix_pyqs_id'), 'pyqs', ['id'], unique=False)
    op.create_index(op.f('ix_pyqs_subject'), 'pyqs', ['subject'], unique=False)
    op.create_index(op.f('ix_pyqs_topic'), 'pyqs', ['topic'], unique=False)
    op.create_index(op.f('ix_pyqs_year'), 'pyqs', ['year'], unique=False)
    op.create_table('study_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', 'ABANDONED', name='planstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('daily_hours', sa.Float(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('plan_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plans_id'), 'study_plans', ['id'], unique=False)
    op.create_index(op.f('ix_study_plans_user_id'), 'study_plans', ['user_id'], unique=False)
    op.create_table('subjects',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('GS1', 'GS2', 'GS3', 'GS4', 'CSAT', 'OPTIONAL', 'CURRENT_AFFAIRS', name='subjectcategory'), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_topics', sa.Integer(), nullable=False),
    sa.Column('completed_topics', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_user_id'), 'subjects', ['user_id'], unique=False)
    op.create_table('user_analytics',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_study_hours', sa.Float(), nullable=False),
    sa.Column('total_topics_completed', sa.Integer(), nullable=False),
    sa.Column('total_revisions', sa.Integer(), nullable=False),
    sa.Column('total_notes_created', sa.Integer(), nullable=False),
    sa.Column('total_pyqs_attempted', sa.Integer(), nullable=False),
    sa.Column('total_answers_evaluated', sa.Integer(), nullable=False),
    sa.Column('total_ai_queries', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('subject_performance', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('weak_subjects', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('strong_subjects', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('weekly_data', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('monthly_data', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('heatmap_data', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_analytics_id'), 'user_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_user_analytics_user_id'), 'user_analytics', ['user_id'], unique=True)
    op.create_table('topics',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'NEEDS_REVISION', name='topicstatus'), nullable=False),
    sa.Column('importance_score', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('study_time_minutes', sa.Integer(), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('last_studied_at', sa.String(length=50), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=False),
    sa.Column('pyq_frequency', sa.Integer(), nullable=False),
    sa.Column('last_asked_year', sa.Integer(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('key_concepts', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_index(op.f('ix_topics_parent_id'), 'topics', ['parent_id'], unique=False)
    op.create_index(op.f('ix_topics_subject_id'), 'topics', ['subject_id'], unique=False)
    op.create_table('answer_evaluations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_image_url', sa.Text(), nullable=True),
    sa.Column('ocr_extracted_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='evaluationstatus'), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('obtained_marks', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('structure_score', sa.Float(), nullable=True),
    sa.Column('content_score', sa.Float(), nullable=True),
    sa.Column('keyword_score', sa.Float(), nullable=True),
    sa.Column('analytical_score', sa.Float(), nullable=True),
    sa.Column('grammar_score', sa.Float(), nullable=True),
    sa.Column('examples_score', sa.Float(), nullable=True),
    sa.Column('overall_feedback', sa.Text(), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('improvements', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('suggested_answer', sa.Text(), nullable=True),
    sa.Column('detailed_feedback', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('time_taken_minutes', sa.Integer(), nullable=True),
    sa.Column('exam_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_evaluations_id'), 'answer_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_answer_evaluations_user_id'), 'answer_evaluations', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.Enum('MANUAL', 'AI_GENERATED', 'SUMMARY', 'FLASHCARD', 'MIND_MAP', 'REVISION', name='notetype'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('flashcards', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('key_points', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('mind_map_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('last_revised_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_index(op.f('ix_notes_subject_id'), 'notes', ['subject_id'], unique=False)
    op.create_index(op.f('ix_notes_topic_id'), 'notes', ['topic_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('revision_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'SKIPPED', 'OVERDUE', name='revisionstatus'), nullable=False),
    sa.Column('confidence_before', sa.Integer(), nullable=False),
    sa.Column('confidence_after', sa.Integer(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revision_history_id'), 'revision_history', ['id'], unique=False)
    op.create_index(op.f('ix_revision_history_topic_id'), 'revision_history', ['topic_id'], unique=False)
    op.create_index(op.f('ix_revision_history_user_id'), 'revision_history', ['user_id'], unique=False)
    op.create_table('study_tasks',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', 'RESCHEDULED', name='taskstatus'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=10), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_tasks_id'), 'study_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_study_tasks_plan_id'), 'study_tasks', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_tasks_plan_id'), table_name='study_tasks')
    op.drop_index(op.f('ix_study_tasks_id'), table_name='study_tasks')
    op.drop_table('study_tasks')
    op.drop_index(op.f('ix_revision_history_user_id'), table_name='revision_history')
    op.drop_index(op.f('ix_revision_history_topic_id'), table_name='revision_history')
    op.drop_index(op.f('ix_revision_history_id'), table_name='revision_history')
    op.drop_table('revision_history')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_topic_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_subject_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_answer_evaluations_user_id'), table_name='answer_evaluations')
    op.drop_index(op.f('ix_answer_evaluations_id'), table_name='answer_evaluations')
    op.drop_table('answer_evaluations')
    op.drop_index(op.f('ix_topics_subject_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_parent_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_user_analytics_user_id'), table_name='user_analytics')
    op.drop_index(op.f('ix_user_analytics_id'), table_name='user_analytics')
    op.drop_table('user_analytics')
    op.drop_index(op.f('ix_subjects_user_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_study_plans_user_id'), table_name='study_plans')
    op.drop_index(op.f('ix_study_plans_id'), table_name='study_plans')
    op.drop_table('study_plans')
    op.drop_index(op.f('ix_pyqs_year'), table_name='pyqs')
    op.drop_index(op.f('ix_pyqs_topic'), table_name='pyqs')
    op.drop_index(op.f('ix_pyqs_subject'), table_name='pyqs')
    op.drop_index(op.f('ix_pyqs_id'), table_name='pyqs')
    op.drop_index(op.f('ix_pyqs_exam'), table_name='pyqs')
    op.drop_table('pyqs')
    op.drop_index(op.f('ix_mock_tests_user_id'), table_name='mock_tests')
    op.drop_index(op.f('ix_mock_tests_id'), table_name='mock_tests')
    op.drop_table('mock_tests')
    op.drop_index(op.f('ix_daily_study_logs_user_id'), table_name='daily_study_logs')
    op.drop_index(op.f('ix_daily_study_logs_id'), table_name='daily_study_logs')
    op.drop_index(op.f('ix_daily_study_logs_date'), table_name='daily_study_logs')
    op.drop_table('daily_study_logs')
    op.drop_index(op.f('ix_current_affairs_published_date'), table_name='current_affairs')
    op.drop_index(op.f('ix_current_affairs_id'), table_name='current_affairs')
    op.drop_table('current_affairs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
