// Auto-generated by scripts/inject-env.mjs — do not edit on CI
export const environment = {
  production: true,
  apiUrl: 'https://your-backend.railway.app/api/v1',
  googleClientId: 'YOUR_GOOGLE_CLIENT_ID',
  appName: 'AI UPSC Study OS',
};
